spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1115
    url: jdbc:mysql://10.10.10.173/seller?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
