spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/seller?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
